name: Cases replication
on: [push]

jobs:
  Replicate_cases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Git configuration
        shell: bash
        run: |-
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Select branch
        shell: bash
        run: |-
          git pull
      - name: Replicate files
        id: changed-files
        uses: tj-actions/changed-files@v19
      - name: List all changed files
        shell: bash
        run: |
          newlang=false
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            if [[ $file == content/*/cases/ ]]; then
              newlang=true
            fi
          done
          if [[ $newlang == false ]]; then
            for file in ${{ steps.changed-files.outputs.added_files }}; do
              if [[ $file == content/*/cases/* ]]; then
                use=$file
                file=${file:8}
                lang=${file:0:2}
                for dir in $(cd content && ls -d */); do
                  if [[ "$dir" != "${lang}/" ]]; then
                    tocopy="content/${dir}cases/${file:9}"
                    if [[ ! -f $tocopy ]]; then
                      echo "Replicating content/$file to ${tocopy}"
                      cp content/${file} ${tocopy}
                    fi
                  fi
                done
              fi
            done
          fi
      - name: Commit and push if changes
        shell: bash
        run: |-
          git add -A
          git commit -m "[bot] Replicated new case(s)" || exit 0
          git push --all origin